-- Create "auth_settings" table
CREATE TABLE "public"."auth_settings" (
  "id" bigserial NOT NULL,
  "updated_at" timestamptz NULL,
  "allow_public_registration" boolean NULL DEFAULT true,
  "require_email_verification" boolean NULL DEFAULT true,
  "require_admin_approval" boolean NULL DEFAULT false,
  "default_user_role" character varying(50) NULL DEFAULT 'user',
  "registration_welcome_email" boolean NULL DEFAULT true,
  "allow_user_invitations" boolean NULL DEFAULT true,
  "invitation_expiry" bigint NULL DEFAULT 7,
  "invite_only_mode" boolean NULL DEFAULT false,
  "session_timeout" bigint NULL DEFAULT 10080,
  "session_idle_timeout" bigint NULL DEFAULT 60,
  "refresh_token_expiry" bigint NULL DEFAULT 30,
  "remember_me_duration" bigint NULL DEFAULT 30,
  "max_login_attempts" bigint NULL DEFAULT 5,
  "lockout_duration" bigint NULL DEFAULT 30,
  "two_factor_authentication" boolean NULL DEFAULT false,
  "two_factor_required" boolean NULL DEFAULT false,
  "enable_o_auth" boolean NULL DEFAULT false,
  PRIMARY KEY ("id"),
  CONSTRAINT "check_single_row_auth" CHECK (id = 1)
);
-- Create "email_settings" table
CREATE TABLE "public"."email_settings" (
  "id" bigserial NOT NULL,
  "updated_at" timestamptz NULL,
  "email_provider" character varying(20) NULL DEFAULT 'smtp',
  "email_enabled" boolean NULL DEFAULT true,
  "email_from_address" character varying(255) NULL,
  "email_from_name" character varying(100) NULL,
  "email_reply_to" character varying(255) NULL,
  "smtp_host" character varying(255) NULL,
  "smtp_port" bigint NULL DEFAULT 587,
  "smtp_username" character varying(255) NULL,
  "smtp_password" character varying(255) NULL,
  "smtp_encryption" character varying(10) NULL DEFAULT 'tls',
  "smtp_auth_method" character varying(20) NULL DEFAULT 'plain',
  "smtp_verify_ssl" boolean NULL DEFAULT true,
  "smtp_timeout" bigint NULL DEFAULT 30,
  "smtp_pool_size" bigint NULL DEFAULT 10,
  "send_grid_api_key" character varying(255) NULL,
  "send_grid_webhook_secret" character varying(255) NULL,
  "mailgun_api_key" character varying(255) NULL,
  "mailgun_domain" character varying(255) NULL,
  "mailgun_region" character varying(10) NULL DEFAULT 'us',
  "ses_access_key_id" character varying(255) NULL,
  "ses_secret_access_key" character varying(255) NULL,
  "ses_region" character varying(50) NULL DEFAULT 'us-east-1',
  "postmark_server_token" character varying(255) NULL,
  "postmark_account_token" character varying(255) NULL,
  "email_footer_text" text NULL,
  "enable_email_notifications" boolean NULL DEFAULT true,
  "send_password_reset_email" boolean NULL DEFAULT true,
  "notify_on_card_assigned" boolean NULL DEFAULT true,
  "notify_on_card_comment" boolean NULL DEFAULT true,
  "notify_on_card_due" boolean NULL DEFAULT true,
  "notify_on_board_invite" boolean NULL DEFAULT true,
  "notify_on_mention" boolean NULL DEFAULT true,
  PRIMARY KEY ("id"),
  CONSTRAINT "check_single_row_email" CHECK (id = 1)
);
-- Create "general_settings" table
CREATE TABLE "public"."general_settings" (
  "id" bigserial NOT NULL,
  "updated_at" timestamptz NULL,
  "app_name" character varying(100) NOT NULL DEFAULT 'Kanban Board',
  "app_url" character varying(255) NOT NULL DEFAULT 'http://localhost:3000',
  "app_logo" text NULL,
  "app_favicon" text NULL,
  "app_description" text NULL,
  "show_announcement_banner" boolean NULL DEFAULT false,
  "announcement_message" text NULL,
  "announcement_type" character varying(20) NULL DEFAULT 'info',
  "default_language" character varying(10) NULL DEFAULT 'en',
  "default_timezone" character varying(50) NULL DEFAULT 'UTC',
  "default_items_per_page" bigint NULL DEFAULT 25,
  "max_file_size" bigint NULL DEFAULT 1024,
  PRIMARY KEY ("id"),
  CONSTRAINT "check_single_row_general" CHECK (id = 1)
);
